language: node_js
node_js:
  - "8"

env:
  global:
    - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage

before_script:
  - yarn global add codeclimate-test-reporter

script:
  - yarn
  - yarn run lint
  - yarn run test --coverage
  - yarn run build

after_script:
  - $TRAVIS_PULL_REQUEST || codeclimate-test-reporter < coverage/lcov.info

cache:
  yarn: true

before_deploy:
  - rm -rf release
  - mkdir -p release
  - for file in ./dist/*; do cp "$file" "${file/dist\/vuetify/release\/vuetify-${TRAVIS_TAG}}"; done

deploy:
  - provider: npm
    email: "john.j.leider@gmail.com"
    api_key: $NPM_API_KEY
    tag: $(node ./build/parse-npm-tag.js)
    skip_cleanup: true
    on:
      repo: vuetifyjs/vuetify
      tags: true
  - provider: releases
    api_key: $GITHUB_API_KEY
    files:
      - "release/vuetify-${TRAVIS_TAG}.css"
      - "release/vuetify-${TRAVIS_TAG}.js"
      - "release/vuetify-${TRAVIS_TAG}.min.css"
      - "release/vuetify-${TRAVIS_TAG}.min.js"
    skip_cleanup: true
    on:
      tags: true
